### ISSUE TITLE
Allow option to keep everyone muted for the first 10 seconds of discussion and allow the reporter to speak first and explain

### ISSUE THREAD

**Issue by starcreep48** [automuteus/automuteus#203]
This is just a suggestion for a feature that could be a nice addition. When the meeting is called or a body is reported, allow the person who reported the body to speak uninterrupted for X amount of time, then after X amount of time, the rest of the people in the discussion are unmuted. Would be nice to have an option to turn this on or off.

**Comment by denverquane** [comment]
I like the idea, but at the moment, we don't have a reliable way of gleaning from that game *which* player called the emergency meeting. At least not yet, but I'm sure the folks working on [the capture repo](https://github.com/denverquane/amonguscapture) would like any help anyone could extend in that department :)
