### ISSUE TITLE
Configurable amonguscapture download link

### ISSUE THREAD

**Issue by t00thpick1** [automuteus/automuteus#348]
I use a customized AmongUsCapture build for my discord(it doesn't output user deaths so the user hosting the capture doesn't get extra info), it would be nice to be able to configure the download link without needing to modify source.

**Comment by CarbonNeuron** [comment]
The latest version of AmongUsCapture also does not output user deaths until discussion starts. 
But besides the point.

**Comment by CarbonNeuron** [comment]
Also, if you're already customizing the capture, disabling or modifying how auto update works or the version finder works should be trivial in MainWindow.xaml.cs and UserDataContext.cs

**Comment by t00thpick1** [comment]
@CarbonNeuron Yeah but I also have to modify the server source to use a different link to point to my version rather than the default.

**Comment by t00thpick1** [comment]
Yeah I mean I have to edit this line and rebuild the docker container every update:  https://github.com/denverquane/automuteus/blob/master/discord/message_handlers.go#L28    Its not hard, but I mean its more effort than just doing a docker pull.

**Comment by Wolfhound905** [comment]
> Yeah I mean I have to edit this line and rebuild the docker container every update: https://github.com/denverquane/automuteus/blob/master/discord/message_handlers.go#L28 Its not hard, but I mean its more effort than just doing a docker pull.

Have github do it for you (•‿•)
