### ISSUE TITLE
Make command arg parsing more sophisticated

### ISSUE THREAD

**Issue by DrewScoggins** [automuteus/automuteus#368]
Currently arg parsing for bot commands just splits the string on spaces with the code below. This means that any command with quoted strings with spaces is not handled correctly. It would be nice to have the parser respect quoted strings as a single block and not split on spaces.

```
args := strings.Split(contents, " ")
```

For example:

```
.au stats g "The Skeld" ->
args[0] = .au
args[1] = stats
args[2] = g
args[3] = The Skeld
```

**Comment by Wolfhound905** [comment]
Instead of The Skeld or Mira-HQ you can just write Skeld or Mira.

**Comment by denverquane** [comment]
Closing as Bot's slash commands make this
