### ISSUE TITLE
[Feature Request] Use Crowdin so people can translate AutoMuteUs

### ISSUE THREAD

**Issue by MatadorProBr** [automuteus/automuteus#383]

**Comment by denverquane** [comment]
AutoMuteUs already has extensive localization support. The full list of languages is listed [here](https://github.com/denverquane/automuteus/tree/master/locales) as well as with the command `.au settings language list`

**Comment by MatadorProBr** [comment]
I just thought it was better because I wanted to translate it into other languages, and since this list doesn’t have all Crowdlin, it would make it easier to put all languages

**Comment by denverquane** [comment]
Hey thanks for submitting this issue; I'd actually never heard of Crowdlin before, but it might be a pretty great option. Maintaining the localizations right now is certainly a pain, anything to make it easier for everyone would be a good option.

I'll look into it, thanks!

**Comment by denverquane** [comment]
Thanks for the suggestion @MatadorProBr (sorry for the late implementation). I've now added support for CrowdIn, you can see the translations here: https://automuteus.crowdin.com/

I will probably merge the i10n branch https://github.com/automuteus/automuteus/pull/457 and make a v7 release in a few days; I have a feeling the auto-generated translations won't be up-to-snuff and will need some modifications 😅
