### ISSUE TITLE
[BUG] Duplicate emojis are registered after some time has passed since the bot was installed.

### ISSUE THREAD

**Issue by yahagi-day** [automuteus/automuteus#405]
**Describe the bug**
When I install the bot, it works fine at first, but after a while, it registers duplicate emoji. However, after a while, the bot will register duplicate pictograms. If the pictogram slots are filled with duplicates, the bot will not work properly.
<img width="373" alt="emote" src="https://user-images.githubusercontent.com/32870950/109373981-6878cd00-78f5-11eb-9841-d542ee7ab822.png">

**Expected behavior**
It will prevent duplicate emoji from being registered.

**Version of bot & capture**
 - Bot: v7-test

**Comment by kurokobo** [comment]
AutoMuteUs checks for existing emoji names at its startup and attempt to add them only if they do not exist. 

The name of the emoji is the same as the alias that can be found in your `Server Settings` > `Emoji`. The correct names are `aured`, `aureddead`, etc. It's not changed between v6 and v7, so there was possibility that the names of existed emojis has changed before by some reason.

Could please check the current alias for each emoji in `Server Settings` > `Emoji`? 
Also, please check the log of creating, updating, and deleting emojis in the `Server Settings` > `Audit Log` by filter `Create Emoji`, `Update Emoji` or `Delete Emoji`.
![image](https://user-images.githubusercontent.com/2920259/109409152-96ccda00-79d3-11eb-85fa-9c01339b9978.png)

**Comment by yahagi-day** [comment]
I have not been able to find any reproducibility of this phenomenon.
After setting EMOJI_GUILD_ID, this phenomenon did not occur.
When an emoji was set as a duplicate, two or more emoji with the same name existed. (The name had not been changed.
I will report back if I can reproduce this.

**Comment by denverquane** [comment]
Closing this issue from inactivity; feel free to reopen if you encounter this issue again
