### ISSUE TITLE
"ERROR: Invalid interpolation format for "image" option in service "automuteus": "denverquane/amongusdiscord:${AUTOMUTEUS_TAG:?err}" and it does not start.

### ISSUE THREAD

**Issue by creeper-0910** [automuteus/automuteus#445]
**Describe the bug**
"ERROR: Invalid interpolation format for "image" option in service "automuteus": "denverquane/amongusdiscord:${AUTOMUTEUS_TAG:?err}" occurs.

**To Reproduce**
Execute this command:
git clone https://github.com/denverquane/automuteus.git
cd automuteus
mv sample.env .env
nano .env
AUTOMUTEUS_TAG=6.15.2
GALACTUS_TAG=2.4.1
DISCORD_BOT_TOKEN="TOKEN"
added.
Execute this command:
docker-compose up
**Expected behavior**
It was supposed to boot correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/56744841/127630265-361c8af9-c464-49b2-8620-89eda1126b24.png)

**Version of bot & capture**
 - Bot: 6.15.2
 - Capture: 4.1.2

**Additional Information**
None

**Comment by kurokobo** [comment]
@creeper-0910 
Thanks for reporting, this problem often occurs when you use an older version of Docker Compose. Older Docker Compose may not be able to understand some syntax such as `?`.

Please upgrade your Docker Compose and try again.
If the problem persists, please let us know the version of Docker and Docker Compose, and the OS on which your Docker is running.
