### ISSUE TITLE
automuteus_windows do not start discord bot

### ISSUE THREAD

**Issue by gosu93** [automuteus/automuteus#499]
Bot token correct, it was works 3 month ago.

Log:
2023/02/17 23:51:32 2.4.3-3d7a51cbe55363f312e8eb23a72e08e1d2c94c48
2023/02/17 23:51:32 [Info] No valid HOST provided. Defaulting to http://localhost:8123
2023/02/17 23:51:32 [Info] No PORT provided. Defaulting to 8123
2023/02/17 23:51:32 [Info] No SERVICE_PORT provided. Defaulting to 5000
2023/02/17 23:51:32 Using capture timeout of 36000 seconds
2023/02/17 23:51:32 Using ./ as the base path for config
2023/02/17 23:51:32 Success in initializing the local Filesystem as the Storage Driver
2023/02/17 23:51:32 Bot is now running.  Press CTRL-C to exit.
2023/02/17 23:51:32 Could not connect Bot to the Discord Servers with error: strconv.ParseInt: parsing "1676608944.080": invalid syntax

**Comment by denverquane** [comment]
Look at the last line of that log message, you have a typo (presumably in your guild id?). There's a . in that id that doesn't belong
